package webcrawler;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class WebcrawlerTest {
    @Test public void testWebcrawlerDoesntCrawlExternal() {
        //WebCrawler7 classUnderTest = new WebCrawler7();
        //assertNotNull("app should have a greeting", classUnderTest);
    }
    
    @Test public void testWebcrawlerMappedStaticFiles() {
        //WebCrawler7 classUnderTest = new WebCrawler7();
        //assertNotNull("app should have a greeting", classUnderTest);
    }
    
    @Test public void testWebcrawlerIsNoDuplicateVisits() {
        //WebCrawler7 classUnderTest = new WebCrawler7();
        //assertNotNull("app should have a greeting", classUnderTest);
    }
    
}
